@host=http://127.0.0.1:5098

GET {{host}}/dinners
Authorization: Bearer ayJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwNDBiOWVkOC1kZTdlLTQxZjctYjRlOC00ZTA3ZWFlMDBkYTYiLCJnaXZlbl9uYW1lIjoiQWRhbSIsImZhbWlseV9uYW1lIjoiRGlja2lzb24iLCJqdGkiOiI1NWFiYzZhNC03OTE1LTQ5OGMtOTQ5MS1hMjUxYjE2ZjE2MGQiLCJleHAiOjE3NjU4MTQ1NzUsImlzcyI6IkJ1YmVyRGlubmVyIiwiYXVkIjoiQnViZXJEaW5uZXJVc2VycyJ9.-O39ic4c_wIPeuPZN2pU3cpEEkY3QiTBzQgS4OCJwIM


