@host=http://localhost:5161
POST {{host}}/auth/register
Content-Type: application/json

{
    "firstName": "Rodney",
    "lastName": "Anonymous",
    "email": "rodney@example.com",
    "password": "thinnestline"
}