@host=http://localhost:5098
@hostId=0f8fad5b-d9cb-469f-a165-70867728950e
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJCdWJlckRpbm5lci5Eb21haW4uVXNlcnMuVmFsdWVPYmplY3RzLlVzZXJJZCIsImdpdmVuX25hbWUiOiJBZGFtIiwiZmFtaWx5X25hbWUiOiJEaWNraXNvbiIsImp0aSI6ImEwZWM3N2ZjLWMxMzMtNGY1MS1hM2E5LTgzYjE5NjExYjIwNCIsImV4cCI6MTc2OTE4Nzk0NSwiaXNzIjoiQnViZXJEaW5uZXIiLCJhdWQiOiJCdWJlckRpbm5lclVzZXJzIn0.z9UeMf5g94JooNLBS_GwLAl9d4IBagZwZlqzQq8VswQ

POST {{host}}/hosts/{{hostId}}/menus
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "hostId": "0f8fad5b-d9cb-469f-a165-70867728950e",
  "name": "Menu",
  "description": "This a list of menu sections",
  "sections": [
    {
      "name": "Section",
      "description": "This is a related list of menu items",
      "items": [
        {
          "name": "Item",
          "description": "Eat me, Drink me."
        }
      ]
    }
  ]
}
