@host=http://localhost:5161
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJkOWI2MTBiMC05OGVhLTQzN2YtYjBjOC0wYWU2MmE3NGQ4MzkiLCJnaXZlbl9uYW1lIjoiYWRhbSIsImZhbWlseV9uYW1lIjoiZGlja2lzb24iLCJqdGkiOiIxYzA3MGY5Ny05MWUyLTRjZmUtYTI0Yy1lNDRmNzFkNTY3NmIiLCJleHAiOjE3MDAxNTkzMDMsImlzcyI6IkJ1YmVyRGlubmVyiwiYXVkIjoiQnViZXJEaW5uZXIifQ.0YRVVTAF3M_ZdzHB0qWxLiCmdSccV4nDkeijQHaWPEA
GET {{host}}/dinners
Authorization: Bearer {{token}}
